print("=== GOOGLE SCHOOL ===")
print("*********************")
print("1. Admission")
print("2. Help")
choose=input("Enter :")
if choose=="1":
    print("Admission Form")
    print("Please Fill-up all the letter in Capital Letter")
    name=str(input("Enter your Name :"))
    father=input("Father's name :")
    mother=input("Mother's Name :")
    age=int(input("Age :"))
    sex=input("sex :")
    Prev=input("Previous School name :")
    Addr=input("Address :")
    email=input("E-mail :")
    cont=int(input("Contact nu. :"))
    Nation=input("Nationality :")
    print("Name :",name)
    print("Email :",email)
    print("Contact number :", cont)
    print("Thanks you so much we'll send your id via mail.")
    print("Have a nice day")
if choose == "2":
    print("HELP")
    print("Editor : H4K3R")
    print("Contact : 7903655397")
    print("Please fill up the adimission form in right way."
          "Neither your id may not be created.")
    print(" Visit this link to view more information.")
    print("www.starkexpoworld.blogspot.com")
    print("Thanks you.")
