print("=== GOOGLE SCHOOL ===")
print("*********************")
print("1. Admission")
print("2. Help")
choose=input("Enter :")
if choose=="1":
    print("Admission Form")
    print("Please Fill-up all the leteres in Capital Letter")
    name=str(input("Enter your Name :"))
    father=input("Father's name :")
    mother=input("Mother's Name :")
    age=int(input("Age :"))
    sex=input("sex :")
    Prev=input("Previous School name :")
    Addr=input("Address :")
    email=input("E-mail :")
    cont=int(input("Contact nu. :"))
    Nation=input("Nationality :")
if choose == "2":
    print("www.starkexpoworld.blogspot.com")
    print("Thanks you.")
